config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  resources :posts do
    resources :comments
    resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def children
    Comment.where(parent_type: 'COMMENT', parent_id: id)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :upload_image

  def count_comments
    Comment.where(post_id: id, parent_type: 'POST').count
  end

  def comments
    Comment.where(post_id: id, parent_type: 'POST')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def redirect_if_not_signed_in
    redirect_to login_path unless user_signed_in?
  end

  def redirect_if_signed_in
    redirect_to root_path if user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = Comment.create(post_id: @post.id,
                              user_id: comment_params[:user_id],
                              content: comment_params[:content],
                              parent_type: comment_params[:parent_type],
                              parent_id: comment_params[:parent_id])
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_type, :parent_id)
          .merge(user_id: current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]
  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @post.likes.create(user_id: current_user.id)
    end
    redirect_to post_path(@post)
  end

  def destroy
    if !already_liked?
      flash[:notice] = 'Cannot unlike'
    else
      @like.destroy
    end
    redirect_to post_path(@post)
  end

  private

  def find_post
    @post = Post.find(params[:post_id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, post_id:
    params[:post_id]).exists?
  end

  def find_like
    @like = @post.likes.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :redirect_if_not_signed_in
  def index
    @posts = Post.order(created_at: :desc).limit(50)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :redirect_if_not_signed_in
  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post)
    else
      redirect_to root_path
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :title, :upload_image)
          .merge(user_id: current_user.id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:firstname,
                                 :lastname,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname,
                                 :lastname,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment_form.html.erb
<div class="panel">
  <div class="panel-body">
  
  <%= bootstrap_form_for([@post, @post.comments.build]) do |f| %>


    <%= f.text_area :content,
                    rows: 2,
                    required: true,
                    minlength: 20,
                    maxlength: 1000,
                    placeholder: "Leave a reply",
                    class: "form-control" %>
                    <%= f.hidden_field :parent_type, value: "COMMENT"%>
                    <%= f.hidden_field :parent_id, value: comment.id%>

    <%= f.submit "Submit comments", class: "btn btn-sm btn-primary pull-right" %>
 </div>
  </div>

<% end %>

<%# <div class="panel">
  <div class="panel-body">
    <textarea class="form-control" rows="2" placeholder="Write a comment?"></textarea>
    <div class="mar-top clearfix">
      <button class="btn btn-sm btn-primary pull-right" type="submit"><i class="fa fa-pencil fa-fw"></i> Submit comment</button>
     
    </div>
  </div>
</div> %>

app/views/comments/_form.html.erb
<div class="panel">
  <div class="panel-body">
  
  <%= bootstrap_form_for([@post, @post.comments.build]) do |f| %>


    <%= f.text_area :content,
                    rows: 6,
                    required: true,
                    minlength: 20,
                    maxlength: 1000,
                    placeholder: "Leave a reply",
                    class: "form-control" %>
                    <%= f.hidden_field :parent_type, value: "POST"%>
                    <%= f.hidden_field :parent_id, value: @post.id%>

    <%= f.submit "Submit comments", class: "btn btn-sm btn-primary pull-right" %>
 </div>
  </div>

<% end %>

<%# <div class="panel">
  <div class="panel-body">
    <textarea class="form-control" rows="2" placeholder="Write a comment?"></textarea>
    <div class="mar-top clearfix">
      <button class="btn btn-sm btn-primary pull-right" type="submit"><i class="fa fa-pencil fa-fw"></i> Submit comment</button>
     
    </div>
  </div>
</div> %>

app/views/layouts/_navigationbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="row">

      <!-- Elements visible all the time -->
      <div class="col-sm-7">
        <%= render "layouts/navigation/header" %>
      </div><!-- col-sm-7 -->

      <!-- Elements collapses on smaller devices -->
      <div class="col-sm-5">
        <%= render "layouts/navigation/collapsible_elements" %>
      </div><!-- col-sm-5 -->

    </div><!-- row -->
  </div><!-- container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggerapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigationbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navigation/_collapsible_elements.html.erb
<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse navbar-right" id="navbar-collapsible-content">
  <ul class="nav navbar-nav ">
    <%= render collapsible_links_partial_path %>
  </ul>
</div><!-- navbar-collapse -->

app/views/layouts/navigation/_header.html.erb
  <% # <div class="navbar-header"> %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Home", root_path, class: "navbar-brand" %>
    <% # </div> %>

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li ><%= link_to "Login", login_path %></li>
<li ><%= link_to "Signup", signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li class="Login"><%= current_user.firstname %></li>
<li ><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>

app/views/pages/index.html.erb
<div class="container cta-100 ">
<div class="container">
<div class="row">
<span class ="page-title col-sm-9 pull-left"><h2>All Posts</h2></span>
  <div class="col-sm-3 pull-right">  <%= link_to "Create Post", new_post_path, class: "btn btn-md btn-primary" %> </div>
    </div>
  <div class="row blog">
    <div class="col-md-12">
       <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="row">
              <%= render @posts %>              
            </div>
          </div>

    </div>
  </div>
</div>
</div>

app/views/posts/_post.html.erb
<div class="col-md-4" >
<div class="item-box-blog">
  <div class="item-box-blog-image">
    <!--Date-->
    <div class="item-box-blog-date bg-blue-ui white"> <span class="mon"><%= post.created_at.strftime("%b") %> <%= post.created_at.strftime("%d") %> <%= post.created_at.strftime("%Y") %></span> </div>
    <!--Image-->
    <figure> <img alt="" src=<%= (url_for(post.upload_image || "")) if post.upload_image.attached? %>> </figure>

  </div>
  <div class="item-box-blog-body">
    <!--Heading-->
    <div class="item-box-blog-heading">
      
        <h5><%= link_to post.title, post_path(post.id) %> </h5>
      
      
    </div>
    <!--Data-->
    <div class="item-box-blog-data" style="padding: px 15px;">
      <p><i class="fa fa-user-o"></i> Posted by: <%= post.user.firstname %> <i class="fa fa-comments-o"></i> Comments(<%= post.comments.count %>)</p>
      <p> <i class="fa fa-thumbs-up"></i> Likes(<%= post.likes.count %>)</p>
    </div>
    <!--Text-->
    <div class="item-box-blog-text">
      <p><%= post.content %></p>
    </div>
    <div class="mt">  <%= link_to "read more", post_path(post.id), class: "btn bg-blue-ui white read" %> </div>
   
  </div>
</div>
</div>

app/views/posts/new.html.erb
<div class="container">
 <div class="row login-form">
  <div class="col-sm-6 col-sm-offset-3">
   <h2 class="text-center">Create New Post</h2>
        <%= render 'posts/new/post_form' %>
  </div>
</div>
</div>

app/views/posts/new/_post_form.html.erb
<%= bootstrap_form_for(@post) do |f| %>
    <%= f.text_field :title,
                     maxlength: 100,
                     placeholder: "Title",
                     class: "form-control",
                     required: true,
                     minlength: 5,
                     maxlength: 100 %>
    <%= f.text_area :content,
                    rows: 6,
                    required: true,
                    minlength: 20,
                    maxlength: 1000,
                    placeholder: "Write your comments here then click Create Post",
                    class: "form-control" %>

                    <%= f.file_field :upload_image, class: "form-control" %>  

    <%= f.submit "Create a post", class: "btn btn-primary btn-block" %>
  <% end %>

app/views/posts/show.html.erb
<div class="container cta-100 ">
<div class="container">
<div class="page-title">
      
<span class ="page-title"><h2><%= @post.title %></h2>

 <p ><i class="fa fa-thumbs-up"></i><%= @post.likes.count %> <%= (@post.likes.count) == 1 ? "Like" : "Likes" %>, 


<% pre_like = @post.likes.find { |like| like.user_id == current_user.id } %>
<% if pre_like %>
You liked this post 
  <%= button_to "Unlike", post_like_path(@post, pre_like), method: :delete, class: "btn btn-sm btn-warning fa fa-thumbs-down" %>
<% else %>
  <%= button_to "Like", post_likes_path(@post), method: :post, class: "btn btn-sm btn-primary fa fa-thumbs-up" %>
<% end %>
</p>


  <div class="row blog">
  <div class="item-box-blog">


  <div class="item-box-blog-image">
    <!--Date-->
    
    <div class="item-box-blog-date bg-blue-ui white"> <span class="mon"><%= @post.created_at.strftime("%b") %> <%= @post.created_at.strftime("%d") %> <%= @post.created_at.strftime("%Y") %></span> </div>
    <!--Image-->
    <figure> <img alt="" src=<%= (url_for(@post.upload_image)) if @post.upload_image.attached? %>> </figure>
  </div>
  <div class="item-box-blog-body">
  
    <div class="item-box-blog-text">
      <p><%= @post.content %></p>
    </div>
   
   
  </div>
</div>
          </div>
        </div>


<span class ="page-title"><h3>Comments (<%= @post.comments.count %>)</h3>

     
<div class="container bootdey">
<div class="col-md-12 bootstrap snippets">
 <%= render "comments/form" %>

<div class="panel">
    <div class="panel-body">
    <!-- Newsfeed Content -->
    <!--===================================================-->
    <% @post.comments.each do |comment| %>
     
    <div class="media-block">
      <a class="media-left img-circle img-sm" href="#"><i class="fa fa-user fa-lg"></i></a>
      <div class="media-body">
        <div class="mar-btm">
          <a href="#" class="btn-link text-semibold media-heading box-inline"><%= comment.user.firstname %></a>
          <p class="text-muted text-sm">
          <%= comment.created_at.strftime("%d") %> <%= comment.created_at.strftime("%b") %> <%= comment.created_at.strftime("%Y") %>  <%= comment.created_at.strftime("%H") %>:<%= comment.created_at.strftime("%M") %>
         </p>
        </div>
        <p><%= comment.content %></p>
        <div class="pad-ver">
        <%= render "comments/comment_form", comment: comment %>
        </div>
        <hr>

       <% comment.children.each do |child_comment| %>
        <!-- Comments -->
        <div>
          <div class="media-block">
            <a class="media-left img-circle img-sm" href="#"><i class="fa fa-user fa-lg"></i></a>
            <div class="media-body">
              <div class="mar-btm">
                <a href="#" class="btn-link text-semibold media-heading box-inline"><%= child_comment.user.firstname %></a>
               <p class="text-muted text-sm">
                <%= child_comment.created_at.strftime("%d") %> <%= child_comment.created_at.strftime("%b") %> <%= child_comment.created_at.strftime("%Y") %>  <%= child_comment.created_at.strftime("%H") %>:<%= child_comment.created_at.strftime("%M") %>
              </p>
              </div>
              <p><%= child_comment.content %></p>
             
              <hr>
            </div>
          </div>
          <% end %>


        </div>
      </div>
    </div>
    <!--===================================================-->
    <!-- End Newsfeed Content -->

<% end %>
  
  </div>
</div>
</div>
</div>